# Generated by Django 4.1.7 on 2023-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=30)),
                ('marca', models.TextField(max_length=30)),
                ('modelo', models.TextField(max_length=30)),
                ('año', models.TextField(max_length=30)),
                ('color', models.TextField(max_length=30)),
                ('precio', models.TextField(max_length=30)),
                ('seguro', models.TextField(max_length=30)),
                ('numPasajeros', models.TextField(max_length=30)),
                ('metodoPago', models.TextField(max_length=30)),
                ('placa', models.TextField(max_length=30)),
            ],
        ),
    ]
