# Generated by Django 4.1.7 on 2023-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('edad', models.TextField(max_length=30)),
                ('sexo', models.TextField(max_length=30)),
                ('celular', models.TextField(max_length=30)),
                ('rh', models.TextField(max_length=30)),
                ('causa', models.TextField(max_length=30)),
                ('diagnostico', models.TextField(max_length=30)),
                ('medicamento', models.TextField(max_length=30)),
                ('costo', models.TextField(max_length=30)),
            ],
        ),
    ]
