# Generated by Django 4.1.7 on 2023-05-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=30)),
                ('raza', models.TextField(max_length=30)),
                ('nombre', models.TextField(max_length=30)),
                ('edad', models.TextField(max_length=30)),
                ('peso', models.TextField(max_length=30)),
                ('color', models.TextField(max_length=30)),
                ('nomDueño', models.TextField(max_length=30)),
                ('guarderia', models.TextField(max_length=30)),
                ('paseador', models.TextField(max_length=30)),
                ('horasPaseo', models.TextField(max_length=30)),
            ],
        ),
    ]
