# Generated by Django 4.1.7 on 2023-04-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=30)),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('correo', models.TextField(max_length=30)),
                ('celular', models.TextField(max_length=30)),
                ('sexo', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='creditoLineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=30)),
                ('nombre', models.TextField(max_length=30)),
                ('montoMax', models.TextField(max_length=30)),
                ('plazoMax', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=30)),
                ('codigo', models.TextField(max_length=30)),
                ('monto', models.TextField(max_length=30)),
                ('plazo', models.TextField(max_length=30)),
                ('desembolso', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=30)),
                ('nombreUser', models.TextField(max_length=30)),
                ('clave', models.TextField(max_length=30)),
            ],
        ),
    ]
