# Generated by Django 4.1.7 on 2023-05-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('numSerie', models.TextField(max_length=30)),
                ('categoria', models.TextField(max_length=30)),
                ('cantidad', models.TextField(max_length=30)),
                ('precio', models.TextField(max_length=30)),
            ],
        ),
    ]
